name: Generate Snake game

on:
  schedule:
    - cron: '0 0 * * *'  # corre una vez al día
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-snake.svg
          gif_out_path: dist/github-snake.gif
          # opcional: puedes cambiar color de la serpiente
          color_snake: '#ff4500'
